require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
AllCops:
  DisplayCopNames: true
  Exclude:
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - .git/**/*
    - bin/*
    - db/**/*
    - !ruby/regexp /\/config\/(?:(?!routes.rb|initializers\/\*).)*$/
Layout/LineLength:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  CountComments: false
  Max: 100
Naming/AccessorMethodName:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundMethodBody:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - lib/ruby/const.rb
    - lib/ruby/const/*
Style/FormatString:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Lint/UnderscorePrefixedVariableName:
  Enabled: false
Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Style/TrailingUnderscoreVariable:
  Enabled: false
Lint/RedundantSplatExpansion:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  ()
    '%i': ()
    '%q': ()
    '%Q': ()
    '%r': ()
    '%s': ()
    '%w': ()
    '%W': ()
    '%x': ()
Style/ZeroLengthPredicate:
  Enabled: false
Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
Style/DoubleNegation:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Style/NilComparison:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false

# ifかunlessかは場合によって選びたい
Style/IfUnlessModifier:
  Enabled: false
# if!とunlessは別物
Style/NegatedIf:
  Enabled: false
# blockで書きたい時もある
Style/SymbolProc:
  Enabled: false
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Lint/UnusedBlockArgument:
  Enabled: false
Performance/RangeInclude:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Rails/FilePath:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Rails/ApplicationController:
  Enabled: false
Lint/NonDeterministicRequireOrder:
  Enabled: false
Rails/UnknownEnv:
  Environments:
    - development
    - test
    - production
    - staging
Rails/HelperInstanceVariable:
  Enabled: false

RSpec/ExampleLength:
    Max: 20
RSpec/MultipleExpectations:
    Max: 5
RSpec/ContextWording:
    Enabled: false
Capybara/FeatureMethods:
    Enabled: false
